# This file was *autogenerated* from the file Data_Plots.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_9 = Integer(9); _sage_const_0p9 = RealNumber('0.9'); _sage_const_0p05 = RealNumber('0.05')
import csv
import os
file_names=os.listdir("./")
Blah = [e for e in file_names if 'Naor' in e]
file_names=[e for e in file_names if 'Random' in e]
file_names=[e for e in file_names if '.csv' in e]
PoA_List=[]

for e in file_names:
    name = e.split(',')
    infile=open(e,'rb')
    input=csv.reader(infile)
    data=[[eval(j) for j in row] for row in input]
    infile.close()
    PoA_List.append([eval(name[_sage_const_1 ]),data[-_sage_const_1 ][-_sage_const_1 ]])

infile = open(Blah[_sage_const_0 ],'rb')
input = csv.reader(infile)
data = [[eval(j) for j in row] for row in input]
infile.close()
Anadata = [[e[_sage_const_1 ],e[-_sage_const_1 ]] for e in data ]
Naordata = [[e[_sage_const_1 ],e[-_sage_const_2 ]] for e in data ]

PoA_List.sort()
p = line(PoA_List,color = 'black',axes_labels=['$\\Lambda$','Average Cost'],legend_label='Heuristic 1',linestyle = '-')
p += line(Anadata,color = 'black',legend_label='Heuristic 2',linestyle = '--')

p.ymin(_sage_const_0 )
p.xmin(_sage_const_0 )
p.set_legend_options(loc = (_sage_const_0p05 ,_sage_const_0p9 ))
p.save("PoA_v_Demand.pdf")

file_names = os.listdir("./")
file_names=[e for e in file_names if 'Ana' in e]
file_names=[e for e in file_names if '.csv' in e]

infile = open(file_names[-_sage_const_1 ],'rb')
input=csv.reader(infile)
data = [[eval(row[_sage_const_0 ]),eval(row[_sage_const_9 ])] for row in input]
p+=list_plot(data,legend_label='Analytical Result',plotjoined=True,color='black',ymin = _sage_const_0 )

p.save("PoA_v_Demand_comparison.pdf")
