# This file was *autogenerated* from the file Analyse.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4)
import os,sys,csv

def evalfail(string):
    try:
        return eval(string)
    except:
        return string

files = os.listdir('.')
Data = []
for e in files :
    if '.csv' in e:
        infile = open(e,'rb')
        input = csv.reader(infile)
        Data.append( [[evalfail(i) for i in row] for row in input])
       #Data.append( [row for row in e])
        infile.close()
p = plot([],axes_labels = ['$ \\lambda $','PoA'])
q = plot([],axes_labels = ['$ \\lambda $','PoA'])
r = plot([],axes_labels = ['$ \\lambda $','Cost'])

r1data = []
r2data = []
r3data = []
colors = rainbow(_sage_const_5 )
for e in Data:
    pdata = []
    qdata = []

    for i in e:
        pdata.append([i[_sage_const_1 ],(i[-_sage_const_4 ]/i[-_sage_const_1 ])])
        qdata.append([i[_sage_const_1 ],(i[-_sage_const_4 ]/i[-_sage_const_2 ])])
        r1data.append([i[_sage_const_1 ],i[-_sage_const_1 ]])
        r2data.append([i[_sage_const_1 ],i[-_sage_const_2 ]])
        r3data.append([i[_sage_const_1 ],i[-_sage_const_3 ]])


    p+= line(pdata,color = 'black')
    q+= line(qdata,color = 'black')

r += line(r1data,color = 'black', legend_label = 'Heuristic 2',linestyle = '--')
r += line(r2data,color = 'black', legend_label = 'Heuristic 3',linestyle = ':')
r += line(r3data,color = 'black', legend_label = 'Heuristic 1',linestyle = '-')

r.save('./costcomp.pdf')
p.save('./Ana.pdf')
q.save('./Naor.pdf')
